config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  get 'signup' => 'users#new'
  post '/signup' => 'users#create'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy',as:'logout'

  resources :users
  resources :sessions

  

   root 'tasks#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user
	validates :status,
				presence:true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :tasks
	validates  :first_name,
				presence:true
	validates  :last_name,
				presence:true
	validates  :email,
				presence:true,
				uniqueness:true
	validates  :password,
				presence:true



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :current_user
	protect_from_forgery with: :exception
	
	private
		def current_user
			
			@current_user ||= User.find(session[:user_id]) if session[:user_id]
		end

		def require_user
			
			redirect_to '/login' unless current_user
		end

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		
		
	end
	def create
		@user=User.find_by_email(params[:session][:email])
		if @user && @user.authenticate(params[:session][:password])
			session[:user_id]=@user.id
			redirect_to '/', notice: "you're logged in as #{@user.first_name} #{@user.last_name}"
		else
			redirect_to '/login', notice: "There seems to be a problem, Please recheck your email and password"
		end
	end

	def destroy

		session[:user_id] = nil 
		reset_session
		redirect_to '/login' ,notice: "you have successfully logged out of your account"
	end
	def index 
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:index, :show]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.where(user_id:current_user.id)
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.user_id=current_user.id if current_user

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit!
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_user, only: [:index, :show]
	def new
		@user=User.new
	end
	def create
		@user=User.new(user_params)

		if @user.save
			flash[:notice]= "account created"
			session[:user_id]=@user.id
			redirect_to '/' 
		else
			redirect_to '/signup', notice:"Fill all the fields correctly"
		end
	end

	def index

		@users=User.all
	end
	

	private
		def user_params
		  params.require(:user).permit(:first_name,:last_name,:email,:password)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsSimpleAuthentication</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-7s5uDGW3AHqw6xtJmNNtr+OBRJUlgkNJEo78P4b0yRw= sha512-nNo+yCHEyn0smMxSswnf/OnX6/KwJuZTlNZBjauKhTK0c+zT+q5JOCx0UFhXQ6rJR9jg6Es8gPuD2uZcYDLqSw==" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha256-KXn5puMvxCw+dAYznun+drMdG1IFl3agK0p/pqT9KAo= sha512-2e8qq0ETcfWRI4HJBzQiA3UoyFk6tbNyG+qSaIBZLyW9Xf3sWZHN/lxe9fTh1U45DpPf07yj94KsUHHWe4Yk1A==" crossorigin="anonymous"></script>
</head>
<body>
<div class="container"%>
	

	<div class="row" id="headrow">
		

		<%if current_user%>
			<ul class="nav nav-tabs nav-justified">
				<!--<%#if params[:controller]!='tasks'%>-->
				<%=link_to "Tasks",tasks_path, class:"btn btn-primary"%>
				<%=link_to "Users",users_path,class:"btn btn-primary"%>
				<p class="floatright-btn" id="useremailid"><%= current_user.email %></p> <br>
			</ul>
			
			<p class="floatright-btn"><%= link_to 'logout',  logout_path,  method: "delete", data: { confirm: 'Are you sure?' } ,class: "btn btn-danger"%></p>
			 	
					
		<%else%>
			<div class="floatright-btn">
				<ul class="nav nav-tabs">
					<%=link_to "Sign up",new_user_path,class: "btn btn-primary"%>
					<%=link_to "log in",'/login',class: "btn btn-primary"%>
				</ul>
		</div>
		<%end%>
	</div>
	<div class="row">
		<div class="col-md-3"></div>
		<div class="col-md-6">
		<%unless flash.empty?%>
			<%flash.each do |key,value|%>
				<div class="flash"><p><%=value%><p></div>
			<%end%>
		<%end%>
		</div>
		<div class="col-md-3"></div>

	</div>
	<div class="row">
		
		<%= yield %>
		
	</div>

		
	
</div>
</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <%= f.text_field :status , :placeholder => "Whats your plan?" %>
 
  <%= f.submit "Create Task" ,class:"btn btn-success"%>
    
<% end %>

app/views/tasks/edit.html.erb
<div class="col-md-4"></div>
<div class="col-md-4">

	<h2>Editing Task</h2>

	<%= render 'form' %>

	<%= link_to 'Show', @task %> |
	<%= link_to 'Back', tasks_path %>
</div>
<div class="col-md-4"></div>

app/views/tasks/index.html.erb
<div class="col-md-2"></div>
<div class="col-md-8">

  



  <table>
    <thead>
      <tr>
        <%unless @tasks.size==0%>
          <th colspan="6"><h2>Tasks</h2></th>
        <%end%>
        <th colspan="3"><%= link_to 'New Task', new_task_path ,class:"btn btn-warning"%></th>
      </tr>
    </thead>

    <tbody>
      <tr>
        
      </tr>
      <%if @tasks.size== 0%>
        <p>Currently there are no tasks created by you , click on New task to create one!</p>
      <%end%>
      <% @tasks.reverse.each do |task| %>
       <!-- <p>current user:  current_user.id%></p><br>
        <p>task user id:  task.user_id%></p><br>-->
        
         
            
               <tr class="status-row">
            
                  <td colspan="6"><li class="status"><%= task.status%></li></td>
                  
                  <td colspan="2"><%= link_to 'Show', task %></td>
                  <td colspan="2"><%= link_to 'Edit', edit_task_path(task) %></td>
                  <td colspan="2"><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
               </tr>
              
       
      <% end %>
    </tbody>
  </table>

  <br>

 
</div>
<div class="col-md-2"></div>
      

app/views/tasks/new.html.erb
<div class="col-md-4"></div>
<div class="col-md-4">		
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>
</div>
<div class="col-md-4"></div>

app/views/tasks/show.html.erb
<div class="col-md-3"></div>
<div class="col-md-6">
<table>
	<tr class="status-row">
		<td colspan="4"><li class="status"><%= @task.status%></li></td>
		<td colspan="2"><%= link_to 'Edit ', edit_task_path(@task) %></td> |
		<td colspan="2"><%= link_to 'Back', tasks_path %></td>
	</tr>
</table>
</div>
<div class="col-md-3"></div>

app/views/users/index.html.erb
<h2>users are</h2>
<ul>
<%@users.each do |user|%>
	<li><%=user.first_name.capitalize%> <%=user.last_name.capitalize%></li>
<%end%>

app/views/users/new.html.erb
<div class="col-md-4"></div>
<div class="col-md-4">
	<h1>Sign up</h1>

		<%= form_for @user do |f| %>
			<%if @user.errors.any?%>
				<div clsss="error_messages">
					<h2>Form is invalid</h2>
					<ul>
						<% @user.errors.full_messages.each do |message|%>
						<li><%= message %></li>
						<%end%>
					</ul>
				</div>
			<%end%>

		    <%= f.text_field :first_name, :placeholder => "First name",class:"formboxes"%><br>
		    <%= f.text_field :last_name, :placeholder => "Last name" ,class:"formboxes"%><br>
		    <%= f.email_field :email, :placeholder => "Email",id:"mail" ,class:"formboxes"%><br>
		    <%= f.password_field :password, :placeholder => "Password" ,class:"formboxes"%><br>
		    <%= f.submit "Create an account", class: "btn btn-success" %><br>
	    <% end %>

</div>
<div class="col-md-4"></div>
			